# Generated by Django 5.0.3 on 2024-03-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('data', models.DateTimeField(verbose_name='Дата публикации')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Комментарий')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('data', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
