# Generated by Django 5.0.3 on 2024-03-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='my_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
