# Generated by Django 5.0.3 on 2024-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_support_nomer_alter_support_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
